# use C-Space for leader
set-option -g prefix C-Space
unbind-key C-Space
bind-key C-Space send-prefix

# split panes using C-h and C-v
unbind-key '"'
unbind-key  %
bind-key h split-window -h
bind-key v split-window -v

# switch panes using vim shortcuts
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

# vi is good
setw -g mode-keys vi

set-option -g default-terminal screen-256color

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Eliminate delay
set -s escape-time 0

# Increase pane number display time
set -g display-panes-time 3000
